/**
 * Deploy the MessageStore contract on the TezosX testnet.
 *
 * Prerequisites:
 *   1. Compile first: npx tsx scripts/compile.ts
 *   2. Have a bootstrap EVM private key
 *
 * Usage:
 *   npx tsx scripts/deploy.ts <evm_private_key>
 *
 * The script reads the compiled artifact from contracts/MessageStore.json
 * and deploys it to the testnet. It outputs the contract address to add to .env.
 */
import { readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { ContractFactory, JsonRpcProvider, Wallet } from "ethers";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PREFIX = process.env.TXPARK_PREFIX ?? "demo";
const RPC_URL = `https://${PREFIX}.txpark.nomadic-labs.com/rpc`;

async function main() {
  const privateKey = process.argv[2];
  if (!privateKey) {
    console.error("Usage: npx tsx scripts/deploy.ts <evm_private_key>");
    process.exit(1);
  }

  // Read compiled artifact (generated by: npx tsx scripts/compile.ts)
  const artifactPath = resolve(__dirname, "../contracts/MessageStore.json");
  let artifact: { abi: any[]; bytecode: string };
  try {
    artifact = JSON.parse(readFileSync(artifactPath, "utf-8"));
  } catch {
    console.error(
      "Compiled artifact not found. Run first:\n  npx tsx scripts/compile.ts"
    );
    process.exit(1);
  }

  const provider = new JsonRpcProvider(RPC_URL);
  const wallet = new Wallet(privateKey, provider);

  console.log("Deploying MessageStore from", wallet.address, "...");

  const factory = new ContractFactory(artifact.abi, artifact.bytecode, wallet);
  const contract = await factory.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("\nDeployed at:", address);
  console.log(`\nAdd to .env:\nVITE_MESSAGE_STORE_ADDRESS=${address}`);
}

main().catch(console.error);
